apiVersion: v1
kind: PersistentVolume
metadata:
  name: todos-pv
spec:
  storageClassName: duck-image-pv
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  local:
    path: /tmp/kube
  nodeAffinity: # only required for local 
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values: 
              - k3d-k3s-default-agent-0
